import type { CounterpartyProfile } from "../counterparty";
import type { ProviderProfile } from "../provider";

export type DpaContext = {
	provider: ProviderProfile;
	counterparty: CounterpartyProfile;
};

export function renderDpaSchedule(ctx: DpaContext): string {
	const controller = ctx.counterparty.legalName;
	const processor = ctx.provider.legalName;
	return `## Schedule C — Data Processing Addendum (GDPR Art. 28)

This Schedule applies where the Service Provider processes personal data on behalf of the Client in the course of providing the Services. Capitalised terms not otherwise defined have the meaning given in the EU General Data Protection Regulation (Regulation (EU) 2016/679, "GDPR") and, where applicable, the UK GDPR.

### C.1 Roles

- **Controller:** ${controller}
- **Processor:** ${processor}

### C.2 Subject matter, duration, nature, purpose

- **Subject matter:** Personal data submitted to or generated by AI agents, models, and tools operated by the Processor on the Controller's instructions.
- **Duration:** the term of the Agreement, plus any applicable retention period set out below.
- **Nature and purpose:** automated processing for the purposes set out in the Agreement (AI architecture, agent operation, advisory).
- **Categories of data subjects:** the Controller's customers, prospects, employees, and contractors, as relevant to the workflow scoped per engagement.
- **Categories of personal data:** business contact data, account identifiers, communications content, and any other categories the Controller chooses to submit. The Controller will not submit special-category data without prior written agreement.

### C.3 Processor obligations

The Processor will:

- process personal data only on the Controller's documented instructions, including with regard to international transfers;
- ensure that personnel authorised to process personal data are subject to confidentiality obligations;
- implement appropriate technical and organisational measures referenced in §C.6;
- assist the Controller, taking into account the nature of processing, in fulfilling data-subject requests and in meeting Articles 32–36 GDPR obligations;
- on termination, return or delete personal data at the Controller's choice, save where storage is required by applicable law.

### C.4 Sub-processors

The Controller authorises the Processor to engage the following categories of sub-processor:

- LLM and model vendors (e.g. Anthropic, OpenAI, open-source model hosts) for inference;
- infrastructure providers (cloud hosting, vector databases, observability, queueing);
- communication and document-handling tools used by the Processor in the engagement.

The Processor will inform the Controller of any new sub-processor with at least 30 days' prior written notice. The Controller may object on reasonable data-protection grounds within that notice period; if the parties cannot agree on a remedy, either party may terminate the affected portion of the Agreement.

### C.5 International transfers

For transfers of personal data outside the European Economic Area or the United Kingdom (as applicable), the parties will rely on the EU Standard Contractual Clauses (Decision 2021/914) and the UK International Data Transfer Addendum (or the UK Addendum to the SCCs), as applicable, deemed incorporated into this Agreement by reference.

### C.6 Technical and organisational measures

The Processor maintains industry-baseline TOMs including:

- encryption in transit (TLS 1.2+) and at rest where supported;
- least-privilege access controls and authenticated identity management;
- audit logging of administrative actions on systems handling personal data;
- vendor-supplied security controls for sub-processed model inference;
- documented incident-response and breach-notification procedure.

### C.7 Personal-data breach

The Processor will notify the Controller without undue delay, and in any case within **72 hours** of becoming aware of a personal-data breach, providing all information reasonably necessary for the Controller to comply with Article 33 GDPR.

### C.8 Audits

The Controller may, at its own cost and on reasonable prior notice (not more than once per 12 months, save where required to investigate a confirmed breach), audit the Processor's compliance with this Schedule. The Processor may discharge audit obligations by providing third-party assurance reports where reasonably available.

### C.9 Termination

On termination of the Agreement, the Processor will, at the Controller's written choice within 30 days of termination, delete or return personal data and destroy existing copies, save where storage is required by Maltese, EU, or UK law.

### C.10 Conflict

In the event of conflict between this Schedule and the body of the Agreement, this Schedule prevails for matters of personal-data processing only.
`;
}
